services:
  web:
    build: .
    container_name: aski-app
    ports:
      - "8082:8082"
    volumes:
      - .:/app
    command: python main.py

  tests:
    build: .
    container_name: aski-tests
    volumes:
      - .:/app
    command: pytest
